src/EhrgoHealth.Web/Areas/Patient/Controllers/HomeController.cs
using EhrgoHealth.Data;
using EhrgoHealth.Web.Areas.Patient.Models;
using EhrgoHealth.Web.Models;
using Fitbit.Api.Portable;
using Hl7.Fhir;
using Hl7.Fhir.Model;
using Hl7.Fhir.Rest;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;

using Microsoft.Owin.Security;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace EhrgoHealth.Web.Areas.Patient.Controllers
{
    public class HomeController : PatientBaseController
    {
        private ApplicationUserManager userManager;
        private IAuthenticationManager authManager;

        public HomeController(ApplicationUserManager userManager, IAuthenticationManager authManager)
        {
            this.userManager = userManager;
            this.authManager = authManager;
        }

        public ActionResult Index()
        {
            var user = this.User.Identity;

            return View();
        }

        public ActionResult CheckAllergy()
        {
            return View();
        }

        public async Task<ActionResult> CheckVerification(Models.Medicine med)
        {
            using(var dbcontext = new ApplicationDbContext())
            {
                var allergyIntolerance = new AllergyIntolerance(Constants.HapiFhirServerBase, userManager, authManager);

                var user = dbcontext.Users.FirstOrDefault(a => a.Email == this.User.Identity.Name);
                int patientID;
                if(user == null || !int.TryParse(user.FhirPatientId, out patientID))
                {
                    return new HttpStatusCodeResult(404, "Patient not found");
                }
                if(string.IsNullOrWhiteSpace(user.FhirPatientId))
                {
                    //todo: figure out what to show if the patient has no fhir data setup
                    return new HttpStatusCodeResult(404, "Patient does not have FHIR data");
                }
                var medications = new List<string>() { med.Name };
                med.Found = await allergyIntolerance.IsAllergicToMedications(patientID, medications);
            }
            return View(med);
        }

        public async Task<ActionResult> History()
        {
            var tuple = await EhrBase.GetMedicationDetails(User.Identity.GetUserId(), userManager);
            if(tuple.Item1 == null)
            {
                return new HttpStatusCodeResult(404, "Patient not found");
            }
            else
            {
                var viewModel = new PatientData() { Medications = tuple.Item1, Patient = tuple.Item2 };
                return View(viewModel);
            }
        }

        public ActionResult AddMedicine(Models.Medicine med)
        {
            EhrBase.AddMedicationOrder(User.Identity.GetUserId(), med.Name);
            return View(med);
        }

        public ActionResult AddAllergy()
        {
            return View();
        }

        public async Task<ActionResult> AllergyHistory(Allergy all)
        {
            var userid = this.User.Identity.GetUserId();
            var ald = new AddAllergyData(userManager, authManager);
            var ls = await ald.GetAllergyList(userid);

            if(all != null && !string.IsNullOrWhiteSpace(all.MedicationName))
            {
                ls.Add(all.MedicationName);
                await ald.AddAllergyToMedication(all.MedicationName, userid);
                if(all.AllAllergies == null)
                {
                    all.AllAllergies = ls;
                }
            }
            else
            {
                all = new Allergy() { AllAllergies = ls };
            }
            return View(all);
        }
    }
}

src/EhrgoHealth.Web/Areas/Staff/Controllers/EhrController.cs
using EhrgoHealth.Web.Areas.Staff.Models;
using EhrgoHealth.Web.Models;
using Hl7.Fhir;
using Hl7.Fhir.Model;
using Hl7.Fhir.Rest;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace EhrgoHealth.Web.Areas.Staff.Controllers
{
    public class EhrController : Controller
    {
        private readonly ApplicationUserManager userManager;

        public EhrController(ApplicationUserManager userManager)
        {
            this.userManager = userManager;
        }

        // GET: Staff/Ehr
        public ActionResult Index()
        {
            //TODO: probably some kind of a page where you can search on patients
            return View();
        }

        // GET: Staff/Ehr/Details/5
        /// <summary>
        /// get a patients details
        /// </summary>
        /// <param name="id">id is a patient id</param>
        /// <returns></returns>
        public async Task<ActionResult> Details(string id)
        {
            var tuple = await EhrBase.GetMedicationDetails(id, userManager);
            if(tuple.Item1 == null)
            {
                return new HttpStatusCodeResult(404, "Patient not found");
            }
            else
            {
                var viewModel = new PatientData() { Medications = tuple.Item1, Patient = tuple.Item2 };
                return View(viewModel);
            }
            //var allergies = new AllergyIntolerance(Constants.IndianaFhirServerBase).GetListOfMedicationAllergies(id, meds.Select(a=>a.))
        }

        [HttpPost]
        public ActionResult Search(string patientSearch)
        {
            using(var dbcontext = new ApplicationDbContext())
            {
                var results = dbcontext
                    .Users
                    .Where(a => a.UserName.Contains(patientSearch) || a.FhirPatientId == patientSearch || a.Id == patientSearch)
                    .Select(a => new SearchResultsItem() { PatientId = a.Id, PatientName = a.UserName, FhirId = a.FhirPatientId })
                    .ToList();
                if(results.Count < 1)
                {
                    return Content("<h4>No Results Found</h4>");
                }
                return View("SearchResultsPartialView", results);
            }
        }

        public ActionResult AddMedicationOrder(string id, string medication)
        {
            //Note: Understand that MedicationOrder and Medications are 1:1 mappings. Not 1:Many.
            //Medications contain information such the name of the manufacturer and name of the drug
            //Medication order contains information about prescriber, the dosage instruction,
            //and the date the medication was prescribed

            EhrBase.AddMedicationOrder(id, medication);

            throw new NotImplementedException();
            return View();
        }
    }
}

src/EhrgoHealth.Web/Areas/Staff/Controllers/HomeController.cs
using EhrgoHealth.Data;
using EhrgoHealth.Web.Areas.Staff.Models;
using EhrgoHealth.Web.Models;
using Fitbit.Api.Portable;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace EhrgoHealth.Web.Areas.Staff.Controllers
{
    public class HomeController : StaffBaseController
    {
        private readonly IAuthenticationManager authManager;
        private readonly ApplicationUserManager userManager;

        public HomeController(ApplicationUserManager userManager, IAuthenticationManager authManager)
        {
            this.userManager = userManager;
            this.authManager = authManager;
        }

        public ActionResult Index()
        {
            var user = this.User.Identity;

            return View();
        }

        public ActionResult CheckAllergy()
        {
            return View();
        }

        public async Task<ActionResult> CheckVerification(Models.Medicine med)
        {
            using(var dbcontext = new ApplicationDbContext())
            {
                var allergyIntolerance = new AllergyIntolerance(Constants.HapiFhirServerBase, userManager, authManager);

                var user = dbcontext.Users.FirstOrDefault(a => a.FhirPatientId == med.UserFhirID);
                int patientID;
                if(user == null || !int.TryParse(user.FhirPatientId, out patientID))
                {
                    return new HttpStatusCodeResult(404, "Patient not found");
                }
                if(string.IsNullOrWhiteSpace(user.FhirPatientId))
                {
                    //todo: figure out what to show if the patient has no fhir data setup
                    return new HttpStatusCodeResult(404, "Patient does not have FHIR data");
                }
                var medications = new List<string>() { med.Name };
                med.Found = await allergyIntolerance.IsAllergicToMedications(patientID, medications);
            }
            return View(med);
        }

        public async Task<ActionResult> Details(Models.Medicine med)
        {
            EhrBase.AddMedicationOrder(User.Identity.GetUserId(), med.Name);

            using(var dbcontext = new ApplicationDbContext())
            {
                var user = dbcontext.Users.FirstOrDefault(a => a.FhirPatientId == med.UserFhirID);

                var tuple = await EhrBase.GetMedicationDetails(user.Id, userManager);
                if(tuple.Item1 == null)
                {
                    return new HttpStatusCodeResult(404, "Patient not found");
                }
                else
                {
                    var viewModel = new PatientData() { Medications = tuple.Item1, Patient = tuple.Item2 };
                    return View(viewModel);
                }
            }
        }
    }
}

src/EhrgoHealth.Web/Controllers/HomeController.cs
using System.Web.Mvc;

namespace EhrgoHealth.Web.Controllers
{
    public class HomeController : Controller
    {
        [Route("~/")]
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Ehrgo Health provides treatment plan verification for patients and their providers";

            return View();
        }

        public ActionResult Patient()
        {
            ViewBag.Message = "EHR Patient Treatment Tracking and Data";

            return View();
        }

        public ActionResult Provider()
        {
            ViewBag.Message = "EHR Provider Treatment Plan Verifier";

            return View();
        }


        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

src/EhrgoHealth.Web/Areas/Staff/Views/Home/CheckAllergy.cshtml
@model EhrgoHealth.Web.Areas.Staff.Models.Medicine
@{
    ViewBag.Title = "Check For Medication Allergy";
}

<h1>Check for Medication Allergies</h1>

<div class="row">
    <div class="col-md-4">
        <img src="~/Content/Images/Medicine.jpg" width="200" height="150" />
    </div>

    <div class="col-md-8">
        @using (Html.BeginForm("CheckVerification", "Home"))
        {
            <div class="row">
                Enter User Fhir ID
            </div>
            <div class="row">
                @Html.TextBoxFor(m => m.UserFhirID)
            </div>
            <div class="row">
                Enter Medication Name (i.e. Hydrocodone)
            </div>
            <div class="row">
                
                @Html.TextBoxFor(m => m.Name)
            </div>
           
            <div class="row">

            </div>
            <div class="row">
                <input type="submit" value="Check Medicine" />
            </div>
            
        }



    </div>
</div>

src/EhrgoHealth.Web/Areas/Staff/Views/Home/CheckVerification.cshtml
@model EhrgoHealth.Web.Areas.Staff.Models.Medicine

@{
    ViewBag.Title = "Check For Medication Allergy";
}

@if (Model.Found)
{
    <h1>WARNING USING @Html.Raw(Model.Name)!</h1>
    <p>The Patient is allergic to this medication based off history!</p>
}
else
{
    <h1>PASS!</h1>
    <p>There is no matching record for <b>@Html.Raw(Model.Name)</b> in the FHIR database for this patient! </p>

    using (Html.BeginForm("Details", "Home"))
    {
        <input type="text" name="UserFhirID" value="@Html.Raw(Model.UserFhirID.ToUpper())" readonly="readonly" />
        <input type="text" name="Name" value="@Html.Raw(Model.Name.ToUpper())" readonly="readonly" />
        <input type="submit" value="Add Medicine to Patient List" />
    }

}

<p>
    <a class="btn btn-default" @Html.ActionLink("Go back to Check Medicine Allergies", "CheckAllergy", "Home") </a>
</p>

src/EhrgoHealth.Web/Areas/Staff/Views/Home/Details.cshtml
@model EhrgoHealth.Web.Areas.Staff.Models.PatientData

<div>
    <h4>Patient Data</h4>
    <hr />
    <dl class="dl-horizontal"></dl>
    @Html.Partial("MedicationTable", Model.Medications)
</div>

src/EhrgoHealth.Web/Areas/Staff/Views/Home/Index.cshtml
<!-- TODO: This will obviously be required to move to the Provider Area later -->
@{
    ViewBag.Title = "Provider";
}

<style>
    .jumbotron {
        padding-top: 5px;
        padding-bottom: 5px;
        margin-bottom: 5px;
        color: inherit;
        background-color: #1186C3;
    }
</style>

<div class="jumbotron">
    <h1 style="text-align:center"><font color="#FFFFFF">Ehrgo Health</font></h1>
    <h2 style="text-align:center"><font color="#FFFFFF">Provider Portal</font></h2>
    <p class="lead">@ViewBag.Message</p>
</div>

<p>
    <h4 style="text-align:center"><i> Ehrgo Health enables medical providers to consume data directly from the patient-maintained system </i></h4>
</p>
<br />
<div class="row">
    <div class="col-md-4">
        <img src="~/Content/Images/doctor_clipboard.png" />
    </div>
    <div class="col-md-4">
        <h2><img src="~/Content/Images/computer.png" />&nbsp;Update/Check Plan</h2>
        <p>
            Check new treatment plan against patient data
        </p>
        <p>
            @Html.ActionLink("Check Medication", "CheckAllergy", "Home", null, new { @Class = "btn btn-default" })
        </p>
    </div>
    <div class="col-md-4">
        <h2><img src="~/Content/Images/prescription_bottle.png" />&nbsp;EHR</h2>
        <p>
            Assign a patient medications
        </p>
        <p>
            @Html.ActionLink("Goto Ehr", "Index", "Ehr", null, new { @Class = "btn btn-default" })
        </p>
    </div>
</div>